// constants.h
#ifndef STRING_NOISE_CONSTANTS_H
#define STRING_NOISE_CONSTANTS_H

#define SHUFFLE 0
#define ASCENDING 1
#define DESCENDING 2
#define RESHUFFLE 3

#define DEFAULT_VOWEL_MASK 0x06
#define DEFAULT_CONSONANT_MASK 0x07
#define DEFAULT_NWS_MASK 0x08
#define DEFAULT_GENERAL_MASK 0x09
#define DEFAULT_2BYTE_MASK 0x0A
#define DEFAULT_4BYTE_MASK 0x0B

#endif // STRING_NOISE_CONSTANTS_H

