// constants.h
#ifndef STRING_NOISE_CONSTANTS_H
#define STRING_NOISE_CONSTANTS_H

#define SHUFFLE 0
#define ASCENDING 1
#define DESCENDING 2
#define RESHUFFLE 3

#define DEFAULT_VOWEL_MASK 0x10
#define DEFAULT_CONSONANT_MASK 0x11
#define DEFAULT_DIGIT_MASK 0x12
#define DEFAULT_NWS_MASK 0x13
#define DEFAULT_GENERAL_MASK 0x14
#define DEFAULT_2BYTE_MASK 0x15
#define DEFAULT_4BYTE_MASK 0x16
#define DEFAULT_END 0x17
#define DEFAULT_END_SPACE 0x18
#define DEFAULT_PAD 0x00


#endif // STRING_NOISE_CONSTANTS_H

